### ISSUE TITLE
Only downloads first chunks

### ISSUE THREAD

**Issue by kevva** [kevva/download#105]
When downloading a file that's larger than the fixture I use in tests, the following promise never resolves https://github.com/kevva/download/blob/master/index.js#L14-L21. To me, the code looks alright, and kinda identical to what it looks in `got`.

@floatdrop, any ideas?

**Comment by sheerun** [comment]
Could you consider rollbacking 5.0.0? It bit me, as the library is unusable as for now

**Comment by sheerun** [comment]
maybe use the same version of get-stream as got (downgrade). it seems stream.then is never firing.

**Comment by floatdrop** [comment]
@kevva I found, that calling get-stream on stream in `response` event is broken – calling it on stream from got is getting data, but it most certainly break tests.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/download/commit/d2ef9c7e6cb99d3d4de7ddf081af43fa7f34bb53.
