### ISSUE TITLE
v5.0.0 breaks usage of download-status

### ISSUE THREAD

**Issue by kevin-smets** [kevva/download#106]
Not sure if I need to report this here as well, but seeing as they're pretty much tied together, I'll repeat the issue here. v5.0.0 breaks usage with download-status.

Original issue: https://github.com/kevva/download-status/issues/13

**Comment by kevva** [comment]
You could implement it manually using something like this https://github.com/visionmedia/node-progress/blob/master/examples/download.js. This module returns a stream so you can just listen on the `data` event.
