### ISSUE TITLE
Is resume supported?

### ISSUE THREAD

**Issue by ohenepee** [kevva/download#109]
Can't seem to find that anywhere in this repo

**Comment by shinnn** [comment]
https://github.com/kevva/download#downloadurl-destination-options

> Returns both a Promise for a Buffer and a Duplex stream 

Duplex stream is resumable since it has Readable interface.

**Comment by ohenepee** [comment]
How exactly does a duplex stream resume and incomplete downloads?

**Comment by shinnn** [comment]
https://github.com/kevva/download#downloadurl-destination-options

> Returns both a Promise for a Buffer and a Duplex stream 

Duplex stream is resumable since it has Readable interface. https://nodejs.org/api/stream.html
