### ISSUE TITLE
Write after end

### ISSUE THREAD

**Issue by dcy0701** [kevva/download#112]
when i sync down 10000 pics，always run into write after end

```
      events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
```

how to solve it?
thx 💃 💃  :D

**Comment by aludvigsen** [comment]
I also got trouble with this error.. and i'm not sure why this is happening

**Comment by sindresorhus** [comment]
Try to narrow down it down to a simplified test case or submit a [failing test](https://github.com/avajs/ava#failing-tests). Not much we can do about the current information.
