### ISSUE TITLE
error when url is too long

### ISSUE THREAD

**Issue by klausgao** [kevva/download#115]
http://wx.qlogo.cn/mmopen/fa15Y55dibibDgXibo7Q0VNBsnjSU2oC9aLEFR8QFmamqxrahjjwiavQL3ibzBWwdGJh0P0bwvzFKu5wGSGowW6UHQ9WUic01qGZ8f/46

http://wx.qlogo.cn/mmhead/PdibpV1sFDHdXE20fAYwpWyEFoiclk0yJ2dicLpSnlMekVV4uwNMfia6pQ/46

try these two urls, the short one can be downloaded, but the long one don't work even without any errors showed.

**Comment by sotojuan** [comment]
This seems to work fine for me. I downloaded the image. What does your code look like?
