### ISSUE TITLE
timeout option seems to have unintended consequences

### ISSUE THREAD

**Issue by aversini** [kevva/download#116]
I'm trying to add a timeout to a download so that if the request takes more than x seconds, I want to drop the call. I've been doing some tests with https://httpbin.org which allows to specify a delay in the url e.g. https://httpbin.org/delay/8 will respond in 8 seconds. I'm trying to create some code that would stop the call after 5 seconds.

Here is my code:
```
var download = require('download');

download('https://httpbin.org/delay/8', {
  timeout: 5000 // hoping to interrupt the call after 5s
}).then(function (body) {
  console.log('==> body: ', JSON.parse(body, 'utf8'));
}).catch(function (err) {
  console.log('==> catch: ', err);
});
```

With no timeout object, I get the response after 8 seconds as expected. But with the 5000ms timeout option here, the call is actually "broken" and lasts at least 1m and 30 seconds and ends with this message:

==> catch:  { RequestError: Connection timed out on request to httpbin.org
    at ClientRequest.req.once.err (/Users/aversin/projects/download/node_modules/got/index.js:70:21)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Timeout.timeoutHandler (/Users/aversin/projects/download/node_modules/timed-out/index.js:12:7)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
  code: 'ETIMEDOUT',
  message: 'Connection timed out on request to httpbin.org',
  host: 'httpbin.org',
  hostname: 'httpbin.org',
  method: 'GET',
  path: '/delay/10',
  bufferedData: <Buffer > }

Am I doing something wrong?
Thanks!

**Comment by sotojuan** [comment]
This is fixed by adding `retries: 0` to the options. Otherwise it'll retry five times by default.

```javascript
download('https://httpbin.org/delay/8', {
  timeout: 5000, retries: 0
}).then(function (body) {
  console.log('==> body: ', JSON.parse(body, 'utf8'));
}).catch(function (err) {
  console.log('==> catch: ', err);
});
```

**Comment by aversini** [comment]
That does the trick! thanks @sotojuan !
