### ISSUE TITLE
Support content-disposition header

### ISSUE THREAD

**Issue by silverwind** [kevva/download#117]
When the server specifies a filename through the `content-disposition` header, it should be used over one generated from the path. This is supported by all browsers, `curl` and `wget` (through options).

There's a handy parser: https://github.com/jshttp/content-disposition#contentdispositionparsestring

**Comment by sindresorhus** [comment]
I don't think @kevva will have time to add this any time soon, but I would be happy to review a pull request.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/kevva/download/pull/122
