### ISSUE TITLE
Error checking ?

### ISSUE THREAD

**Issue by athlordJojo** [kevva/download#121]
i want to update from version 4 to 5, but i have problems to figure out how error handling works with this verison. So, how can i add a callback to, which is triggered, when the download failed? 

This is my current code. What do i need to add to get called when an download failed ? 
      Download(url).then(function (data) {
        fs.writeFileSync(pathToFile, data);
      });

**Comment by athlordJojo** [comment]
ok, after some try and error i found the solution. Easy if to know HOW. Perhabs edding to the readme would be nice...

      Download(url).then(function (data) {
        fs.writeFileSync(pathToFile, data);

      }).catch(function(err){
        // go, do your error handling...
      });

**Comment by kevva** [comment]
This is just how promises work. It's documented here https://github.com/kevva/download#downloadurl-destination-options. I'm assuming that consumers of this module knows how they work.
