### ISSUE TITLE
Support rfc5987 filename in Content-Disposition

### ISSUE THREAD

**Issue by silverwind** [kevva/download#128]
See the `filename*` directive [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#Directives). This directive is used to encode UTF-8 filenames as HTTP headers must only contain ASCII characters. Examples based on the RFC:

````
filename*=iso-8859-1'en'%A3%20rates
filename*=UTF-8''%c2%a3%20and%20%e2%82%ac%20rates
````

I think we can use [this module](https://www.npmjs.com/package/rfc2231) to parse the directive.

**Comment by kevva** [comment]
Tried using the module with our tests but it returned `attachment; filename="dispo.zip`(notice the missing `"` at the end) which caused the `content-disposition` module to throw.

**Comment by silverwind** [comment]
Another module to try: https://github.com/Myhlamaeus/rfc-5987-encoding (This encoding is quite hard to search for because as far as I know, it has no name).

**Comment by silverwind** [comment]
Actually I think this is a non-issue after testing parsing a few headers with just `content-disposition`:

````js
> require("content-disposition").parse("attachment; size=1049971; filename*=iso-8859-1'fr'Fran%E7ais.txt").parameters.filename
'Français.txt'
> require("content-disposition").parse("attachment; size=1049971; filename*=utf-8''%F0%9F%98%81%F0%9F%98%82.txt").parameters.filename
'😁😂.txt'
> require("content-disposition").parse("attachment; size=1049971; filename=notused; filename*=utf-8''SBD%20%C5%A0kodov%C3%A1k%2Ejpg").parameters.filename
'SBD Škodovák.jpg'
> require("content-disposition").parse("attachment; size=1049971; filename=notused; filename*=utf-8''%F0%9F%98%81%F0%9F%98%82.txt").parameters.filename
'😁😂.txt'
````

Looks pretty correct alread to me 😉

**Comment by silverwind** [comment]
Yeah, [not an issue](https://github.com/jshttp/content-disposition/blob/70084f83d5ccb9ce8288fc57dcd38976a3f48fbd/index.js#L256-L264), sorry for not reasearching enough :)

**Comment by kevva** [comment]
Would've liked if we supported [this](https://github.com/jshttp/content-disposition/issues/2) which the module you linked at first does. Might be an edge case though.

**Comment by silverwind** [comment]
Looks like a dead standard to me, but i'd be nice to have support in https://github.com/jshttp/content-disposition, not this module.

**Comment by kevva** [comment]
Yeah, dead standard indeed. But unsure how often you encounter it. Anyway, I'm going to have a look at it and do a PR to them.

**Comment by yassern** [comment]
Trying to download a excel file, for example: https://www.cepea.esalq.usp.br/br/indicador/series/boi-gordo.aspx?id=2, I am getting the error `TypeError: invalid parameter format`.
