### ISSUE TITLE
When downloading a zip file when the error

### ISSUE THREAD

**Issue by yuxiaoyan1205** [kevva/download#138]
download--http://192.168.2.237:8899/ZIP/5975681569e5f4941e595640.zip--failed--RangeError 
: Array buffer allocation failed

**Comment by kevva** [comment]
That's because you're running out of memory. We're storing the file in memory if you're using the Promise based API. Try using streams instead:

```js
download('unicorn.com/foo.zip').pipe(fs.createWriteStream('foo.zip'));
```

**Comment by yuxiaoyan1205** [comment]
Hi,kevva:
I use streams:download('unicorn.com/foo.zip').pipe(fs.createWriteStream('foo.zip'));
but it is still error:
![image](https://user-images.githubusercontent.com/25838030/28514282-0bd106be-708c-11e7-8c54-4f925f69690f.png)
The size of this zip package is 1.2G。

**Comment by kevva** [comment]
Are you running this in the browser?

**Comment by yuxiaoyan1205** [comment]
yes

**Comment by kevva** [comment]
I'm pretty sure that won't work. This package is intended for use in Node.js.

**Comment by yuxiaoyan1205** [comment]
OK，thanks
