### ISSUE TITLE
Convert to binary string

### ISSUE THREAD

**Issue by labo28** [kevva/download#140]
Is there a way to convert the downloaded file directly to a binary string and return it with a return.

```
function readImgData(imgUrl){
  var download = require("download")

  var buffer = download(imgUrl).then(data => { console.log(data)});
  return buffer;
```

The result of console.log(data) is:
```<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 91 00 00 00 91 08 02 00 00 00 4c ba cd 74 00 00 00 09 70 48 59 73 00 00 0b 13 00 00 0b 13 01 ... >```

**Comment by kevva** [comment]
No, it's an async operation so you would have to do:

```js
function readImgData(url) {
	const download = require('download);
	return download(url);
}

readImgData('foo.png').then(data => {
	doSomeThingWithImg(data);
});
```
