### ISSUE TITLE
Remove gulp-util

### ISSUE THREAD

**Issue by amaujipe** [kevva/download#150]
I'm using your plugin in a personal project. But it have some warnings with gulp-util. Can you follow this recomendations to remove that?

gutil.File => https://www.npmjs.com/package/vinyl
gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
gutil.colors => https://www.npmjs.com/package/ansi-colors
gutil.date => https://www.npmjs.com/package/date-format
gutil.log => https://www.npmjs.com/package/fancy-log
gutil.template => https://www.npmjs.com/package/lodash.template
gutil.env => https://www.npmjs.com/package/minimist
gutil.beep => https://www.npmjs.com/package/beeper
gutil.noop => https://www.npmjs.com/package/through2
gutil.isStream => Use the .isStream() method on Vinyl objects
gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
gutil.isNull => Use the .isNull() method on Vinyl objects
gutil.linefeed => Use the string '\n' in your code
gutil.combine => https://www.npmjs.com/package/multipipe
gutil.buffer => https://www.npmjs.com/package/list-stream
gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by DvStephen** [comment]
@andresjim this package hasn't used this `gulp-util` dependency for a long time, so you should look at whatever package is using an older version of this.

**Comment by michaeljota** [comment]
@DvStephen The package that use `gulp-util` is other package of this same author. I came here to see if this module can stop using the module using `gutil`, but I guess it can't.

**Comment by DanielRuf** [comment]
It is already removed since a few releases. https://github.com/kevva/download/commit/49d6bcbbfb2c784397b72ab7bda820079aeebf15#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by michaeljota** [comment]
As I said, not this particular package, but one from the same author.

**Comment by DanielRuf** [comment]
The answer was meant for other readers and commenters ;-)

**Comment by michaeljota** [comment]
Oh! Sorry. :p

**Comment by silverwind** [comment]
Please upgrade your version of `download`.
