### ISSUE TITLE
Add a cookie option that allows a custom cookie to be set for the download

### ISSUE THREAD

**Issue by diwu1989** [kevva/download#28]

**Comment by anasqadrei** [comment]
Help. How did you do that?

**Comment by diwu1989** [comment]
this library evolved a lot and in the current version, from reading the source code, i dont see how you can set the custom cookie

**Comment by anasqadrei** [comment]
I'm using version 4 of the library. Do you know how to set the cookie in that version?

**Comment by SamVerschueren** [comment]
As this module in the background just passes options down to `got`, as described [in the docs](https://github.com/kevva/download#options), you could have a look at the [cookies](https://github.com/sindresorhus/got#cookies) section.
