### ISSUE TITLE
timeout causes error

### ISSUE THREAD

**Issue by zettam** [kevva/download#36]
When download is created with a timeout, and when it is called multiple times (for look, or asynch.each) it generates the error:

    Error: callback() can only be called once.

Codebit:

	function downloadFiles() {
		async.each(toDownload, function (p, done) {
			var download = new Download({
				timeout: 10000,
				pool: {
					maxSockets: Infinity
				}
			}).get(p).dest(dldir);

			download.run(function (err, files, stream) {
				if (err) {
					errorFiles.push(p);
				} else {
					console.log("Downloaded");
				}
				done();
			});
		}, function (err) {
			if (err) console.log(err);
			console.log("")
		});
	};

**Comment by kevva** [comment]
This works fine for me:

```js
var Download = require('download');
var download = new Download({
    timeout: 1000,
    pool: {
        maxSockets: Infinity
    }
});

var files = [
    'https://raw.githubusercontent.com/imagemin/imagemin/master/test/fixtures/test.gif',
    'https://raw.githubusercontent.com/imagemin/imagemin/master/test/fixtures/test.jpg',
    'https://raw.githubusercontent.com/imagemin/imagemin/master/test/fixtures/test.png',
    'https://raw.githubusercontent.com/imagemin/imagemin/master/test/fixtures/test.svg'
].forEach(dl.get.bind(dl));

dl.dest(__dirname);
dl.run();
```
