### ISSUE TITLE
Allow to define destination for each get

### ISSUE THREAD

**Issue by piranna** [kevva/download#38]
```.dest()``` method define the location of all the downloads, and if you call it several times the last one wins. In that case, it would be better to download to that location only the ones defined after calling to ```.dest()```, being by default the current dir. It's said, that internally each download store the location where it must be downloaded.

**Comment by piranna** [comment]
Having back that ```dest``` parameter would be great :-)

**Comment by piranna** [comment]
Any update on this?

**Comment by kevva** [comment]
Fixed by https://github.com/kevva/download/commit/1d11b913b3b845cfa2e2cb853a16454bd0165a04.

**Comment by piranna** [comment]
Great, thanks! :-D
