### ISSUE TITLE
global process events

### ISSUE THREAD

**Issue by piranna** [kevva/download#39]
When downloading several files at a time, the progress callback (for example when using [download-status](https://github.com/kevva/download-status)) should notify the progress globally instead of for each individual download progress.

**Comment by kevva** [comment]
Might be hard to do since everything is done concurrently, i.e all files is downloaded at the same time.

**Comment by piranna** [comment]
Now that several files can be downloaded concurrently and there's a global tasks array, maybe each one of the downloads instead of emit the events themselves would emit them internally, being the Download manager that listen to them and emit the progress events for the total of them.

**Comment by kevva** [comment]
Still trying to figure out how to do this now that I'm using `got` instead of `request`.

**Comment by piranna** [comment]
Yes, I've also seen that you removed the events so download-status could be used... :-/

**Comment by piranna** [comment]
This is still happening in 4.1.0.

**Comment by kevva** [comment]
Yes, I don't think I'll add global events in the near future.

**Comment by piranna** [comment]
If it's not possible to have a global progress bar, one for each download would be a good thing, although dificult. It could be done by using store & restore cursor position commands.

**Comment by floatdrop** [comment]
Wat. :horse:

**Comment by piranna** [comment]
Cool, I'll try it later.
