### ISSUE TITLE
Extract and download in parallel

### ISSUE THREAD

**Issue by piranna** [kevva/download#40]
When downloading several files, currently it's being waited to finish all of them previously to decompress them. They should be done at the same time, so when one finish to download it can start to decompress while other start downloading.

**Comment by kevva** [comment]
Good idea, I'll try to figure something out.

**Comment by piranna** [comment]
Maybe it can be done by adding the extract tasks to a queue so only one of them is extracting at each time. Unluckily async.js doesn't allow to add tasks to already running executions... :-(

**Comment by kevva** [comment]
Yeah, we'd probably need an `extract` event, but it seems kinda overkill to add that to all the decompress plugins just because of this module.

**Comment by kevva** [comment]
Fixed by https://github.com/kevva/download/commit/bf0d278cbf5b76ce4b3ef0db3891297aa0b38df8.

**Comment by piranna** [comment]
Thank you :-)
