### ISSUE TITLE
strip option is wrong

### ISSUE THREAD

**Issue by piranna** [kevva/download#42]
According to the [docs](https://github.com/kevva/download#strip) it's behaviour is equivalent to ```--strip-components``` for tar. That argument only strip the first directories until it finds one that has a file or several directories, but ```download``` and ```decompress``` modules are doing it for all the files, making the decompression wrong. This is particular a problem for Java namespaced classes, where is usual to have several chained namespace folders.

**Comment by kevva** [comment]
True, it's more a wording issue than a real issue because it's the expected behaviour. PR welcome.

**Comment by piranna** [comment]
Wording issue? What's the expected behaviour for ```download```, work as ```tar```, or strip them all? I think the first one...

**Comment by kevva** [comment]
Strip the number of paths you're specifying. I imagine it'll be much slower to search all folders for files too.

**Comment by piranna** [comment]
I've tried to use it without the ```strip``` argument and the error persists, so maybe it's on the decompress code... The file that's giving me problems is http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.gz, it's raising the next error:

```
/home/piranna/Dropbox/Proyectos/NodeOS/NodeOS/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain/node_modules/download/node_modules/decompress-unzip/node_modules/adm-zip/headers/entryHeader.js:140
                throw Utils.Errors.INVALID_CEN;
                                  ^
Invalid CEN header (bad signature)
```

and inspecting the files that has decompressed already, you can see that there's a lot of .class Java files that should not be there.

**Comment by kevva** [comment]
Probably a adm-zip error.

**Comment by piranna** [comment]
What is adm-zip?

**Comment by shinnn** [comment]
> What is adm-zip?

https://github.com/cthackers/adm-zip

**Comment by piranna** [comment]
I'm extracting a .tar.gz file, not a .zip one...

**Comment by kevva** [comment]
Yeah, that's weird. It thinks it's a zip file for some reason.

**Comment by piranna** [comment]
And what can we do, then?

**Comment by kevva** [comment]
I'll have to check why it's handled as a zip file.

**Comment by kevva** [comment]
@piranna, does this still happen?

**Comment by kevva** [comment]
I've changed the wording in https://github.com/kevva/download/commit/95eebc630c59ad045cddeffdbe5cf2ccb97e5145#diff-0730bb7c2e8f9ea2438b52e419dd86c9R63.

**Comment by piranna** [comment]
Sorry, I was not able to test it since I need support for ```download-status``` and on 4.0.1 is not available. I have tested it by disabling download-status and seems it worked oncem but no more.

**Comment by piranna** [comment]
Could you be able to publish 4.0.1 to npm?

**Comment by piranna** [comment]
Ok I've just checked it and the problem still exist, ```download``` is extracting wrongly the files. Not only it looses execution bit permissions, but also some files and folders are missing. The files on the right are being downloaded and extracted by a shell script, the ones on the right are the same but using ```download``` 4.0.1 instead:

![pantallazo-piranna mabuk -home-piranna-proyectos-nodeos-node_modules-nodeos-barebones-node_modules-nodeos-cross-toolchain](https://cloud.githubusercontent.com/assets/532414/6793252/34614596-d1c2-11e4-9391-2fbe6f2d0301.png)

The scripts for each download are:

```bash
#!/usr/bin/env bash

SOURCES=`pwd`/deps
TOOLS=`pwd`/tools


# Dependencies versions

BINUTILS_VERSION=2.24
GCC_VERSION=4.7.3
#GCC_VERSION=4.9.2
LINUX_VERSION=4.0-rc5
MUSL_VERSION=1.0.4


# Dependencies URLs

BINUTILS_URL=http://ftpmirror.gnu.org/binutils/binutils-$BINUTILS_VERSION.tar.gz
GCC_URL=http://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz
#LINUX_URL=https://www.kernel.org/pub/linux/kernel/v3.x/linux-$LINUX_VERSION.tar.xz
LINUX_URL=https://www.kernel.org/pub/linux/kernel/v4.x/testing/linux-$LINUX_VERSION.tar.xz
MUSL_URL=http://www.musl-libc.org/releases/musl-$MUSL_VERSION.tar.gz


#
# binutils
#

SRC_DIR=$SOURCES/binutils
if [[ ! -d $SRC_DIR ]]; then
  mkdir -p $SRC_DIR                                                  &&
  curl -L $BINUTILS_URL | tar xzf - -C $SRC_DIR --strip-components=1 || exit 10
fi


#
# gcc
#

SRC_DIR=$SOURCES/gcc
if [[ ! -d $SRC_DIR ]]; then
  mkdir -p $SRC_DIR                                             &&
  curl -L $GCC_URL | tar xzf - -C $SRC_DIR --strip-components=1 &&
  (
    cd $SRC_DIR

    # Patch GCC to work with musl
    curl -L http://patches.clfs.org/embedded-dev/gcc-4.7.3-musl-1.patch | patch --silent -Np1 || exit 20

    # Download source code of mpfr, gmp & mpc
#    contrib/download_prerequisites
    mkdir -p mpfr && curl -L http://ftpmirror.gnu.org/mpfr/mpfr-3.1.2.tar.xz | tar xJf - -C mpfr --strip-components=1 &&
    mkdir -p gmp  && curl -L http://ftpmirror.gnu.org/gmp/gmp-6.0.0a.tar.xz  | tar xJf - -C gmp  --strip-components=1 &&
    mkdir -p mpc  && curl -L http://ftpmirror.gnu.org/mpc/mpc-1.0.2.tar.gz   | tar xzf - -C mpc  --strip-components=1 || exit 21
  ) || exit $?
fi


#
# Linux kernel headers
#

SRC_DIR=$SOURCES/linux
if [[ ! -d $SRC_DIR ]]; then
  mkdir -p $SRC_DIR                                               &&
  curl -L $LINUX_URL | tar xJf - -C $SRC_DIR --strip-components=1 || exit 30
fi


#
# musl
#

SRC_DIR=$SOURCES/musl
if [[ ! -d $SRC_DIR ]]; then
  mkdir -p $SRC_DIR                                              &&
  curl -L $MUSL_URL | tar xzf - -C $SRC_DIR --strip-components=1 || exit 40
fi


# Check system headers
if [[ ! -r /usr/include/rpc/types.h ]]; then
  su -c 'mkdir -pv /usr/include/rpc'
  su -c 'cp -v sunrpc/rpc/*.h /usr/include/rpc'
fi
```

```Javascript
#!/usr/bin/env node

var Download = require('download');
//var progress = require('download-status');


// Source versions

const BINUTILS_VERSION = "2.24"
const GCC_VERSION      = "4.7.3"  // "4.9.2"
const LINUX_VERSION    = "4.0-rc5"
const MUSL_VERSION     = "1.0.4"


// Source URLs

const BINUTILS_URL = "http://ftpmirror.gnu.org/binutils/binutils-"+BINUTILS_VERSION+".tar.gz"
const GCC_URL      = "http://ftpmirror.gnu.org/gcc/gcc-"+GCC_VERSION+"/gcc-"+GCC_VERSION+".tar.gz"
//const LINUX_URL    = "https://www.kernel.org/pub/linux/kernel/v3.x/linux-"+LINUX_VERSION+".tar.xz"
const LINUX_URL    = "https://www.kernel.org/pub/linux/kernel/v4.x/testing/linux-"+LINUX_VERSION+".tar.gz"
const MUSL_URL     = "http://www.musl-libc.org/releases/musl-"+MUSL_VERSION+".tar.gz"


Download({ extract: true, strip: 1 })
.get(BINUTILS_URL, 'deps/binutils')
.get(GCC_URL,      'deps/gcc')
.get(LINUX_URL,    'deps/linux')
.get(MUSL_URL,     'deps/musl')
//.use(progress())
.run(function(error)
{
  if(error) throw error;

  console.log('Download finished!');
})
```

So no, definitely this is not fixed.

**Comment by shinnn** [comment]
@piranna For the present you can run built-in `tar` command from `child_process.exec` instead.

**Comment by kevva** [comment]
@piranna, the original issue was resolved (regarding the wording). Can you open a new one about the issues you're having now?

**Comment by piranna** [comment]
> Can you open a new one about the issues you're having now?

Done.
