### ISSUE TITLE
TypeError: Object #<Download> has no method 'use'

### ISSUE THREAD

**Issue by nantas** [kevva/download#45]
I have code like this:
```js
var Download = require('download');
var progress = require('download-status');
var download = new Download({extract: false, mode: '755'})
                                  .get(url)
                                  .dest(cachePath)
                                  .use(progress());
```

When executing, the error in title shows up.

Not sure what's going on there, it used to work a week ago. Is there any api update in v4.0.0 that can cause an issue like this?

**Comment by kevva** [comment]
Yeah, use 3.x.x in case you need "plugin" functionality. It was removed in https://github.com/kevva/download/commit/f1db98ef44604eb69813decb34ef7e78c58fbd96. I'm planning to add something similar back in but I just don't know how it should look yet.
