### ISSUE TITLE
When file contain parameters, it's get ENOENT error

### ISSUE THREAD

**Issue by motizharfati** [kevva/download#48]
try download this:
http://media.shironet.mako.co.il/media/performers/heb/0/905/profile/905_t275.jpg?rnd=33

**Comment by kevva** [comment]
How does your code look? The filename will be `905_t275.jpg?rnd=33`.

**Comment by motizharfati** [comment]
Something like this:
var Download = require('download');

var download = new Download({ strip: 1, mode: '755'})
    .get('http://media.shironet.mako.co.il/media/performers/heb/0/905/profile/905_t275.jpg?rnd=33')
    .dest('c:\\');

download.run(function (err, files) {
    if (err) {
        throw err;
    }
    console.log('File downloaded successfully!');
});

It's happen in windows, you are not allowed to save images with marks like "?"...
If i add a rename command:
.rename('bla.jpg');
it works... so you should prevent marks like "?" on windows.

**Comment by shinnn** [comment]
@motizharfati Could you show us the error log on your console?

**Comment by shinnn** [comment]
@motizharfati And [markdown syntax highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) helps the maintainers to read your code.

```js
var download = new Download({ strip: 1, mode: '755'})
.get('http://media.shironet.mako.co.il/media/performers/heb/0/905/profile/905_t275.jpg?rnd=33')
.dest('c:\');

download.run(function (err, files) {
if (err) {
throw err;
}
console.log('File downloaded successfully!');
});
```

**Comment by motizharfati** [comment]
Hi shinnn, thanks for the feedback.
I can't give you the error log now, i am at work...
Will try to do it tomorow evening.

**Comment by shinnn** [comment]
I can successfully run @motizharfati's code on my Mac OS X.

Probably [the character limitation on Windows file system](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions) causes the error:

> The following reserved characters:
>
> * < (less than)
> * > (greater than)
> * : (colon)
> * " (double quote)
> * / (forward slash)
> * \ (backslash)
> * | (vertical bar or pipe)
> * ? (question mark)
> * * (asterisk)

**Comment by kevva** [comment]
Would it be a good idea to maybe use [filenamify](https://github.com/sindresorhus/filenamify)?

ping @sindresorhus.

**Comment by sindresorhus** [comment]
@kevva Yes.
