### ISSUE TITLE
Request: Fire events for each percentage of download

### ISSUE THREAD

**Issue by cohix** [kevva/download#49]
I would like the ability to register an event handler similar to this:
```
download.on('progress-update', function(percentage)
{
    console.log(percentage + "%");
});
```
To get progress updates during large file downloads.

**Comment by mukeshm** [comment]
Is there any way we can get download progress. The use API is removed in the latest version.

**Comment by kevva** [comment]
Nope, I'd use `3.x.x` (`npm install download@3`) for that. Documentation can be found here https://github.com/kevva/download/tree/v3.3.0.

**Comment by stevemao** [comment]
@kevva why is that? I feel like many missing features I'd see in the latest are in `3.x.x` :)
