### ISSUE TITLE
is_url_superb prevents downloading from intranet domains

### ISSUE THREAD

**Issue by chris-t-reilly** [kevva/download#50]
The is_url_superb package throws an error when dealing with domains defined on the local intranet (example .local domains). Can I suggest/contribute a validateURL option?

**Comment by sindresorhus** [comment]
Exposing that would be leaky abstraction.

@kevva I see no reason for doing such a strict check on the input. Maybe add a `loose` mode option in `is-url-superb` that `download` could use which allowed any kind of domain?

**Comment by chris-t-reilly** [comment]
Yes, that's much better API-wise.

**Comment by kevva** [comment]
Would probably need to add it in `url-regex` first.
