### ISSUE TITLE
Incorrect extraction

### ISSUE THREAD

**Issue by piranna** [kevva/download#54]
As pointed at https://github.com/kevva/download/issues/42#issuecomment-85255868, extraction of files sometimes is incorrect, leading to don't maintain the execution bit and also missing files and folders.

**Comment by kevva** [comment]
The file modes should be fixed but the missing files and folders in the `gcc` package is due to some `@LongLink` issue. Open an issue at https://github.com/mafintosh/tar-stream about it.

**Comment by piranna** [comment]
Linux kernel also had (bigger) problems when extracting, so I think is also used there.

**Comment by piranna** [comment]
Files mode is fixed.

**Comment by piranna** [comment]
Issue for tar-stream at https://github.com/mafintosh/tar-stream/issues/35

**Comment by mafintosh** [comment]
Just published tar-stream 1.1.4 which has support for gnu long link/path.

**Comment by kevva** [comment]
Sick.

**Comment by shinnn** [comment]
:clap:
