### ISSUE TITLE
Support .xz format

### ISSUE THREAD

**Issue by piranna** [kevva/download#55]
When trying to extract a .tar.xz file, it maintain the original file instead of extracting it. Using .tar.gz works correctly.

**Comment by shinnn** [comment]
I couldn't find good modules to extract xz from https://www.npmjs.com/.

If you want to resolve this issue,

1. Create a module to extract xz written in JavaScript
2. Create [decompress](https://github.com/kevva/decompress/)-tarxz plugin
3. Create a PR to add `.tarxz` method to [decompress](https://github.com/kevva/decompress/)

**Comment by piranna** [comment]
I've found several ones...

https://www.npmjs.com/package/xz
https://www.npmjs.com/package/node-liblzma
https://www.npmjs.com/package/lzma-native

Also some of them in pure Javascript:

https://github.com/cscott/lzma-purejs
https://github.com/nmrugg/LZMA-JS

**Comment by kevva** [comment]
Open an issue at https://github.com/kevva/decompress.

**Comment by piranna** [comment]
Done.
