### ISSUE TITLE
Re-enable support for download-status

### ISSUE THREAD

**Issue by piranna** [kevva/download#56]
On 4.x.x, support for download-status was removed, so now there's no way to have a feedback of the current progress. Since now several files can be downloaded at once, it would be ok, if the download progress is the total of all the files, but a better option is to have support for an independent progress for each file if they don't interfere in the screen.

**Comment by kevva** [comment]
Yup, just need https://github.com/sindresorhus/got/pull/41 to be merged.

**Comment by piranna** [comment]
Thank you.
