### ISSUE TITLE
Add files to current download instance

### ISSUE THREAD

**Issue by piranna** [kevva/download#57]
Allow to add a file to be downloaded to a current executing instance, updating the global process statistics

**Comment by kevva** [comment]
This is never going to work since `.run()` needs to finish.

**Comment by piranna** [comment]
Isn't there any sort or queue where to add files to be downloaded? Should I use a new Download instance?

**Comment by kevva** [comment]
You can add as many files as you want before executing `.run()`. If you want to download more files after you have to use a new instance, yes.

**Comment by piranna** [comment]
Ok, I hope could be able to add them later, too.
