### ISSUE TITLE
Run return stream

### ISSUE THREAD

**Issue by TrySound** [kevva/download#60]
Can run return stream of `cb(err, files)` like [here](https://github.com/gulpjs/gulp-util#buffercb) ?

**Comment by shinnn** [comment]
https://github.com/kevva/download/issues/47#issuecomment-75623188

@TrySound Any use case?

**Comment by TrySound** [comment]
@shinnn Using with gulp plugins, but download will be instead of gulp.src

**Comment by kevva** [comment]
@TrySound, use the `.use()` method.
