### ISSUE TITLE
Lastest version doesn't work with download-status

### ISSUE THREAD

**Issue by bennyschudel** [kevva/download#67]
For me the file has zero length when using in combination with download-status?

Any one else?

**Comment by idpaterson** [comment]
Same behavior here downloading, for example, https://s3.amazonaws.com/awv-api/awv_api.zip which works fine without using download-status. Using the extract option and download-status, I am left with a zero-byte file named awv_api.zip rather than an extracted awv_api directory.

**Comment by Agrosis** [comment]
download-status uses the res.on('data', function(data){...}) call, so I'm thinking that it overrides the original  'data' event.

**Comment by idpaterson** [comment]
@Agrosis, I agree. Commenting this out allows the zip file to extract properly:
```js
res.on('data', function (data) {
	bar.tick(data.length);
});
```

**Comment by Agrosis** [comment]
I'm using 3.3.0 for download now, and everything works as it should. I'm assuming some code was changed for handling stream data.
