### ISSUE TITLE
Error: EACCES

### ISSUE THREAD

**Issue by artem-malko** [kevva/download#71]
Error: EACCES, open '/Users/a.malko/Sites/tars/tars--new-master/.tmpTemplater/tars-handlebars-master/.gitignore

I downloaded some code from github without any options, except one:
```javascript
new Download({ extract: true })
```
If I call it with sudo — it works fine, but it's not cool.

**Comment by floatdrop** [comment]
@artem-malko seems like you have done something under sudo, how about `chown -R /Users/a.malko a.malko`?

**Comment by artem-malko** [comment]
@floatdrop 
I've made it.
But:
```javascript
~/Sites/tars/tars--new-master/.tmpTemplater master *= $ ls -ll
total 0
d---------  2 a.malko  1673768055  68 Jul 21 22:18 tars-handlebars-master
~/Sites/tars/tars--new-master/.tmpTemplater master *= $
```

tars-handlebars-master — it is a folder, which is been downloaded by "download".

**Comment by artem-malko** [comment]
@floatdrop I've fixed it. Just use { mode: '755' } and everything will be ok)

**Comment by floatdrop** [comment]
@kevva should `755` be default value of `mode`?

**Comment by artem-malko** [comment]
@floatdrop  +1
