### ISSUE TITLE
Middleware is executed twice if request is redirected

### ISSUE THREAD

**Issue by vweevers** [kevva/download#74]
When a request is redirected (a 302 in my case), I found that [stream.on('response')](https://github.com/kevva/download/blob/c352736d7e484fdeba12a218d83227657bfd8ad4/index.js#L125) fires twice, and therefore `this.ware.run(..)` too, which trips the `download-status` plugin (it writes "fetch" twice and a whole bunch of newlines on end).

I'm not sure whether the issue is with `download` or `download-status`.

**Comment by floatdrop** [comment]
This can be fixed by updating `got` to newer version. Can't do it by myself now - could you make a pr please?

**Comment by floatdrop** [comment]
@vweevers thank you! :sparkles:
