### ISSUE TITLE
Feature - progress event

### ISSUE THREAD

**Issue by facultymatt** [kevva/download#75]
It would be useful to have a callback or event emit on download progress. Ideally as percent of total if content-length is provided by source.

**Comment by Jielde** [comment]
+1

**Comment by floatdrop** [comment]
@facultymatt @Jielde you can implement it as a plugin (`download-progess` for example) that will emit these events on stream. Look at https://github.com/kevva/download-status as example.

**Comment by kevva** [comment]
I'm returning the whole stream now so you can listen on the `data` event on the `response`.
