### ISSUE TITLE
Broken support for installs without git/github access

### ISSUE THREAD

**Issue by huerlisi** [kevva/download#81]
The following commit introduced a git version as dependency: 7ab93281

This broke installations without installed git or that are behind proxies.

**Comment by shinnn** [comment]
This will be fixed when @kevva publishes `decompress` v3.0.0 to npm. The reason why I introduced https://github.com/kevva/download/commit/7ab93281276b9705e86fa899e454bbc0625572e5 is that I don't have npm access to [`decompress`](https://www.npmjs.com/package/decompress) module.

**Comment by shinnn** [comment]
@huerlisi For now you can set some npm configs to enable proxy. https://docs.npmjs.com/misc/config

**Comment by kaldrenon** [comment]
@shinnn I am experiencing this issue as well, and am disallowed (by company policy) from using a proxy to bypass the problem.

Is there an ETA on the publish?

**Comment by shinnn** [comment]
> Is there an ETA on the publish?

I don't know. Only @kevva knows.

**Comment by kaldrenon** [comment]
Understood - thanks for the quick reply

**Comment by netei** [comment]
Same problem for me.

**Comment by shinnn** [comment]
> Is there an ETA on the publish?

// @kevva

**Comment by kevva** [comment]
Sorry, I've added you to `decompress` on npm @shinnn.

**Comment by shinnn** [comment]
Fixed in v4.4.1. https://github.com/kevva/download/commit/eb40273d2ea80fd29a1eada0398e28122d2f921b
