### ISSUE TITLE
First stream chunk is missed for plugins

### ISSUE THREAD

**Issue by piranna** [kevva/download#83]
I've found that `duplexify` module [consume the first data chunk](https://github.com/mafintosh/duplexify/blob/a15c3f87d4443ea58005c5c9488e56e06842b2b3/index.js#L161-L163) from the streams, so when using a plugin that need to have access to all its content like [download-checksum](https://github.com/piranna/download-checksum) it fails. The key is when the [response](https://github.com/kevva/download/blob/bac7dd9913302c37564b087f9e198658f5692234/index.js#L125-L129) event is called, that `duplexify` has already consumed it. I've done a workaround by looking for the missing data chunk [on the internal buffers](https://github.com/piranna/download-checksum/blob/1108d6c664906eb3012b1d8fd1a938871d73b704/index.js#L14-L17) and inject it on my plugin hash function, but don't know if there's a better way to do it, besides the fact that `duplexify` shouldn't consume it, but I've tried to disable it and doesn't work... :-/

/cc @mafintosh

**Comment by kevva** [comment]
Plugins are removed now.
