### ISSUE TITLE
Decompress on real time

### ISSUE THREAD

**Issue by piranna** [kevva/download#88]
Download waits until the files get completely downloaded before to extract them, making it to consume a lot of memory. Files should be decompress and extracted at the same time they are being downloaded, making it faster and using less memory. This would be fairly easy by using the Streams API on the plugins and the different steps of the decompress pipeline.

**Comment by derhuerst** [comment]
As a note: Back in September, I had a [build script that – using streams – downloaded and extracted a zip file from GitHub](https://github.com/derhuerst/vbb-static/blob/06754cb30dd68e4b4b5a9b0051da163777b1af6e/build/01-download.coffee#L30-L32). This was *really* unreliable, I got a lot of errors, zlib complaining about errors in the stream.

**Comment by piranna** [comment]
I've tried something similar using Node.js native `http` module, `async.js` and `maybe-gunzip` but when the first download finished all the downloads got trucated... :-/

**Comment by kevva** [comment]
Yeah, this won't be supported. Read https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api for why.

**Comment by piranna** [comment]
The point of this request is to not load the full file on memory before to decompress it, that makes it unusable for memory constrained systems.

Being an issue only related to just a file format, it doesn't makes sense to not implement it on the other ones that are capable to have a streams-based usage, and maybe if you don't want to do it with zip files because they are not designed for this, emulate that behaviour by loading the full file on memory (but only this file format), or maybe better storing it on a temporal file on the hard-disk and start dispatching stream events when file is fully downloaded.

As I've said, this is not a real-time problem but mostly a memory constrained systems problem, only that having a real-time behaviour has other advantages. I think this issue should be re-open, but if you don't want to implement real-time features due to zip file format, would you consider to re-open it if I change the title to specify the memory usage problem?

**Comment by piranna** [comment]
Other option would be, to remove all decompressors to external modules and people use whatever they wants, so some of them can have real-time downloading and extraction and others don't...

**Comment by kevva** [comment]
You could do this manually by piping `download` to whatever decompressor you want. E.g:

```js
const dl = download('foobar.com/file.zip);

dl.pipe(gunzip()).pipe(process.stdout);
```

**Comment by piranna** [comment]
Is this a new feature? Is this compatible with the decompress feature?

**Comment by kevva** [comment]
Well, yeah, it's a part of the new `5.0.0` version. But you won't be able to use `decompress` with streams though.

For `tar` files, you can use https://github.com/mafintosh/tar-stream.

**Comment by kevva** [comment]
@piranna, FYI, I'm adding streams to `decompress` so this might work in the near feature.

**Comment by piranna** [comment]
> @piranna, FYI, I'm adding streams to decompress so this might work in the near feature.

Cool, thanks! :-D

**Comment by kevva** [comment]
Not for `zip` files though, but for `tar`, `tar.gz` and `tar.bz2` it should work.

**Comment by piranna** [comment]
> Not for zip files though, but for tar, tar.gz and tar.bz2 it should work.

It could do the work by the moment, we could be able later to enable it for `.zip` files too, both by using a streams-based zip decompressor or if you want to stick to being spec compliant by emulating the stream behaviour after the zip file has been fully downloaded (it's only just a matter of emit `data` events...).
