### ISSUE TITLE
Parameter files is an empty array

### ISSUE THREAD

**Issue by songxc** [kevva/download#89]
Hi, Kevva:

I found a problem of the download module this morning, the parameter files is an empty array.
You can run the demo below, and It will be result in a ``[]``.

    var Path = require('path');
    var Download = require('download');
    
    // 下载路径
    var destDir = Path.join(__dirname, './download');
    
    // 下载图片
    new Download({mode: '755'})
      .get('http://songxc.github.io/images/thumbnail-2.png', destDir)
      .run(function(err, files) {
        if (err) {
          throw err;
        }
        console.log(files);
      });

demo address: <https://github.com/songxc/node-demo/blob/master/download.js>

**Comment by kevva** [comment]
Try `5.0.0`. Report back if you experience any problems.
