### ISSUE TITLE
Download synchronous

### ISSUE THREAD

**Issue by MakhouT** [kevva/download#90]
Can you add a feature that let's you download files synchronously. Instead all at the same time. I'm passing a lot of links but it's not handling it well as there are a lot of files to download. Some files don't finish downloading, this is also seen in download-status.

**Comment by shinnn** [comment]
Thanks for the suggestion but probably we won't implement this feature. Synchronous HTTP request is totally a bad practice.

**Comment by kevva** [comment]
Yup, what @shinnn said.
