### ISSUE TITLE
Filename not preserved when URL contains query string parameters

### ISSUE THREAD

**Issue by abejfehr** [kevva/download#91]
For example, a download from a link like the following:

_https://s3-eu-west-1.amazonaws.com/dev.abcd.uploads.eu-west/abcd123.pdf?X-Amz-Content-Sha256=abc&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ABC/20160209/eu-west-1/s3/aws4_request&X-Amz-Date=20160209T134951Z&X-Amz-SignedHeaders=Host&X-Amz-Expires=3600&X-Amz-Signature=abcd123_ (not a real link, content has been changed for security)

Will result in a filename like `abcd123.pdf!X-Amz-Content-Sha256=abc`, instead of just `abcd123.pdf`

**Comment by edclement** [comment]
I can't even seem to get it to work with url's that contain query params in v5

**Comment by silverwind** [comment]
This could be fixed by parsing the URL:

```js
> const uri = "https://s3-eu-west-1.amazonaws.com/dev.abcd.uploads.eu-west/abcd123.pdf?X-Amz-Content-Sha256=abc&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ABC/20160209/eu-west-1/s3/aws4_request&X-Amz-Date=20160209T134951Z&X-Amz-SignedHeaders=Host&X-Amz-Expires=3600&X-Amz-Signature=abcd123"
> path.basename(url.parse(uri).pathname)
'abcd123.pdf'

**Comment by sindresorhus** [comment]
I don't think @kevva will have time to fix this any time soon, but I would be happy to review a pull request.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/kevva/download/pull/122.
