### ISSUE TITLE
Problems with evil eval in transitive dep got -> create-error-class.

### ISSUE THREAD

**Issue by hedefalk** [kevva/download#94]
I'm having problems with eval that happens on load of this library. Stuff has been fixed upstream, but the version of got used by downloads latest release is still bad.

Pretty please, is it possible to release an update that uses got@^6.0.0. 

See: https://github.com/ensime/ensime-node/issues/8

**Comment by shinnn** [comment]
https://github.com/kevva/download/pull/95#issuecomment-205725634
