### ISSUE TITLE
Rename and extract do not work together

### ISSUE THREAD

**Issue by mrjonny2** [kevva/download#96]
If you add rename to the file it will not be extracted
`new Download({mode: '755', extract: true})
	.get(contentURL + URLfileName)
	.dest('cache')
	.run(function(err, files){
		if (err) {
			return callback(err, files)
		}
		return callback(err, files)
	})`
That works but if I add 
`.rename(fileName)`
Anywhere in that it will no longer extract the file

**Comment by kevva** [comment]
The `.rename` method is removed now.
