### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by screendriver** [kevva/download#97]
I am using [download-cli](https://github.com/kevva/download-cli) in one of my npm scripts and try to download a file from a self signed https URL.

Unfortunately I get the error

```
unable to verify the first certificate
```

Is it possible to ignore that and to accept self signed certificates?

**Comment by screendriver** [comment]
Update: I saw that it is **not** a self signed certificate. It is issued by my company and I have to import it our root certificate to my keychain. Then it should work.

Apart from this: would be an option to add an argument like in `wget` called `--no-check-certificate` or something like this?

**Comment by kevva** [comment]
Should be fixed in https://github.com/kevva/download/commit/559a6f5d576a9f8e3e929f2ae83f19cd14379ad9.
