### ISSUE TITLE
Different directory and rename

### ISSUE THREAD

**Issue by screendriver** [kevva/download#98]
I am using [download-cli](https://github.com/kevva/download-cli) in one of my npm scripts. Is it possible to add a different output directory **and** a different file name? Like

```sh
$ ./node_modules/.bin/download -o myDir http://test.com/foo.json > bar.json
```

If I make this one above I get a `bar.json` in the root directory but not in `myDir`.

**Comment by kevva** [comment]
`download http://test.com/foo.json > myDir/bar.json`

**Comment by screendriver** [comment]
But this does not work when the directory `myDir` does not exist. `-o myDir` however creates not existing directories.
